config:
  models:
    whisper: large-v3
    pyannote: pyannote/speaker-diarization-3.1 # huggingface 
    llama_summarize:
      model_name: bartowski/Mistral-Nemo-Instruct-2407-GGUF
      file_name: Mistral-Nemo-Instruct-2407-Q6_K_L.gguf
      starting_context_size: 24

  prompts:
    summarize: |
      "As analyst, your task is to write a meeting summary in {output_language} based on the transcription of a meeting in {output_language}

      The summary must be in bullet points, strictly in {output_language}, organized into three sections:
        -key points: include all the main arguments and topics discussed
        -action points: list alla action discussed. If no actions, suggest possible actions.
        -technical and non-technical details: provide any additional information, both technical and non-technical, with clarity and accuracy.
      
      For example, if the output language is Italian, use the following sections: "Punti chiave, Punti d'azione, Dettagli tecnici e non".
      
      Each bullet point should be detailed as necessary to capture all relevant information.

      All sections must be as comprehensive and easy to understand, others will grasp the meeting's content.
      
      The document must be written in {output_language}. If the language is not recognized or detected or it does not match {output_language}, the document will be rejected.

      The user will prompt only the transcription of the meeting, and you will reply only with the content of the document, written in markdown.
      "