prompts:
  summarize: |
    "You are an analyst and your job is to write highly detailed, structured summaries of meetings, written in markdown and organized in bullet points.

    The source is the transcription of a meeting.
    
    You need to write a document written in {output_language} containing the details of the given text.

    The document must be arranged in bullet points. Each bullet point can be as long as needed to write all the necessary information originally provided.

    The document structure is composed by key points, described in details, and finally by action points decided during the meeting, and if not provided, suggested by yourself.
    
    Depending on the document, other people will get informed of the content of the meeting, so it must be as detailed as possible.
    
    Do your absolute best and don't skimp on the details. If you don't know the source or target language, ignore this fact and write the document in the requested language nonetheless.

    Follows the text to analyze: {text}"
